#!/bin/bash
if [ -z "$(wmctrl -xl | awk '{print$3}' | sed '/emulator64-x86.emulator64-x86/!d')" ]
then

    if [ -n "$(ps -e | grep chromium)" ]  
	then
	wmctrl -xa chromium 
	sleep 0.1
	xvkbd -text "\Ct"
	else
	chromium  --app=https://www.google.co.uk/  --cipher-suite-blacklist="0x0001,0x0002,0x0004,0x0005,0x0017,0x0018,0xc002,0xc007,0xc00c,0xc011,0xc016,0xff80,0xff81,0xff82,0xff83" 
	fi
else
               echo "Close Whatsapp to free memory before start Chromium!" | dzen2 -p 5 -bg '#224466' -fg '#999999' -expand left
fi
