#!/bin/bash
if [ -z "$(wmctrl -xl | awk '{print$3}' | sed '/emulator64-x86.emulator64-x86/!d')" ]
then

	if [ -n "$(ps -e | grep chromium)" ]  
	then
	wmctrl -xa chromium
	sleep 0.1
	xvkbd -text "\Ct"
	else
	chromium
	fi
else
               echo "Close Whatsapp to free memory before start Chromium!" | dzen2 -p 5 -bg '#224466' -fg '#999999' -expand left
fi
