#!/bin/bash
function isnumeric {
if [ -n "`echo $1 | sed 's/[0-9]//g'`" ]; then
    echo '1' #is not numeric 
else
    echo '0' #is numeric
fi
}
function ischar {
if [ -n "`echo $1 | sed 's/[0-Z]//g'`" ]; then
    echo '1' #is not characters 
else
    echo '0' #is characters
fi
}

cd $HOME
IWCONFIG="`iwconfig wlp2s0`"
ESSID="`echo $IWCONFIG | awk '{ printf$4}' |sed -e 's-ESSID:\(\)-\1-' -e 's-"--g'`"
ESSID1="`echo $ESSID | sed -e 's/\///g' -e 's/\_//g' -e 's/offany//'`"
QUALITY="`echo $IWCONFIG | awk '{ printf$26 }' | sed -e 's-Quality=\([0-9][0-9]\)/70-\1-g'`" 
POWER="`echo $IWCONFIG | awk '{ printf$28 }' | sed -e 's.level=-\([0-9][0-9]\).\1.g'`"
PING="`ping -c 1 -W 1 www.google.es | grep -o "time=.*" | sed 's/time=\([0-9]....*\)ms/\1/g'`"
PING=${PING%.*}
if [ -n "$ESSID1" ] && [ "`ischar "$ESSID1"`" -eq '0' ]
then 
ESSIDC="\nESSID= $ESSID"
fi
if [ -n "$QUALITY" ] && [ `isnumeric "$QUALITY"` -eq '0' ]
then 
QUALITY=$(( $QUALITY * 100 / 70 ))
QUALITYC="\nQUALITY= $QUALITY%"
fi
if [ -n "$POWER" ] && [ `isnumeric "$POWER"` -eq '0' ]
then 
POWER=$(( 120 - $POWER ))
POWERC="\nPOWER= $POWER%"
fi
if [ -n "$PING" ] && [ `isnumeric "$PING"` -eq '0' ]
then 
PINGC="\nPING= $PING ms"
fi

if [ $PING -lt 1000 ]
then
echo -e "the connection is OK\n $ESSIDC$QUALITYC$POWERC$PINGC"
	else echo "the connection isn't working"
fi
