#! /bin/bash
FONT=Arial
BGCOLOR="#224466"
FGCOLOR="#999999"

function func {
FG="$2"
BG="$1"
#CROSS="^ib(1)^fg("$FG")^bg("$BG")x^p(-13)^co(17) ^ib(0)"
CROSS=" (x)"
CROSS1=" (x)"
#CROSS="^i($HOME/x.xpm)"
#CROSS1="^i($HOME/x-12.xpm)"
while true;
do
i=0
CMD="wmctrl -ia "
CMDx="wmctrl -ic "
WINDOWS=($(wmctrl -l | sed '/kype/d' | sed -e 's/blas\@equipob:/Xterm$/' | awk '{print$4$5$6$7}' | tr "\n" " " )) 
WINDOWS_ID=($(wmctrl -xl | sed '/kype/d' | awk '{print$1}' | tr "\n" " " ))
CURRENT_WORKSPACE="$(wmctrl -d | sed '/\*/!d' | awk '{print$1}')"
CURRENT_WINDOW_ID="$(wmctrl -l | sed '/[0-f]\ \ '$CURRENT_WORKSPACE'\ /!d' | tail -n 1 | awk '{print$1}')"
while [ "$i" -lt "${#WINDOWS[*]}" ]
do
	if [ "${WINDOWS_ID["$i"]}" = "$CURRENT_WINDOW_ID"  ]
	then
	DZENLINE["$i"]="$(echo "^fg($BG)^bg($FG) ^ca(1, $CMD ${WINDOWS_ID["$i"]})${WINDOWS["$i"]}^ca()^ca(1, $CMDx ${WINDOWS_ID["$i"]})"$CROSS1"^ca()")"
	else
	DZENLINE["$i"]="$(echo "^fg($FG)^bg($BG) ^ca(1, $CMD ${WINDOWS_ID["$i"]})${WINDOWS["$i"]}^ca()^ca(1, $CMDx ${WINDOWS_ID["$i"]})$CROSS^ca()")"
	fi
	i=$(($i+1))
done
echo "^bg($FG)^fg($BG) $(($CURRENT_WORKSPACE+1)) ^bg(#446688)^fg($FG) ^ca(1,  skype_script ) Skype ^ca()${DZENLINE[*]} "
DZENLINE=()
sleep 2;
done;
}

function weatherf {
while true;
do
echo "^fg(white)$(head -n1 $HOME/.weatherforecast | sed 's/Estas en/You are in/g ') $moonstateswitch^ca(1,  "libreoffice $HOME/.weatherforecast") $(rain | head -n1)^ca()"
sleep 30
done
}

function values { 
while true
do 
CPUTEMP="$(sensors | sed -e '/Core/!d' -e 's/+\([0-9][0-9]\.[0-9]°C\).*/ \1 /' -e 's/\ //g' | tr "\n" " ")"
echo " $(battery_status)$CPUTEMP ^ca(1, zenity --calendar) $(date +%H:%M:%S) ^ca()" 
sleep 1  
done
}

(values   | dzen2 -fn $FONT -title-name dzenc -y -1 -ta center -expand left -bg $BGCOLOR -e 'entertitle=exec:;leavetitle=exec:' )&
(weatherf | dzen2 -fn $FONT -title-name dzenb -y -1 -ta center -bg $BGCOLOR -expand right  -e 'entertitle=exec:;leavetitle=exec:' )&
(func $BGCOLOR $FGCOLOR | dzen2 -fn $FONT -title-name dzena -ta center -expand right -bg $BGCOLOR -e 'entertitle=exec:;leavetitle=exec:' -dock )&

#install "wmctrl" from the official repositories
#add this to make work "wmctrl" in xmonad
#import XMonad.Hooks.EwmhDesktops
#main = xmonad $ ewmh defaults
#add this to your xmonad.hs file to make space in your screen
# manageHook = manageDocks <+> [whatever you had before]]
#myLayout =      avoidStruts $
#		[whatever you had before]
