#! /bin/bash
function rains {
BGCOLOR="Black"
FGCOLOR="#999999"
output=""
if [ ! -e ./.weatherforecast ]; then output= "No weatheforecast data stored"; else
	RAINvector=($(cat ./.weatherforecast | awk '{print$5}' | sed -n '/[0-9]/p' | sed -n '1,24 p' | tr "\n" "\ "))	
 	TIMEvector=($(cat ./.weatherforecast | awk '{print$1}' | sed -n '/[0-9]/p' | sed -n '1,24 p' | tr "\n" "\ ")) 
	i=0
 	while [ "$i" -lt "${#RAINvector[*]}" ]
	do
		if [ "${RAINvector["$i"]}" -ge 10 ]	
		then	
				output=""${TIMEvector[$i]}" It will rain a lot "
                break
			else
			if [ "${RAINvector["$i"]}" -ge 5  ]	
			then	
					output=""${TIMEvector[$i]}" It will rain "
                    break
				else
				if [ "${RAINvector["$i"]}" -ge 1 ]	
				then	
					output=""${TIMEvector[$i]}" It will rain a bit ";
                    break
				fi
			fi
		fi
		i=$(($i+1))
	done	
fi
echo "^bg($BGCOLOR)^fg($FGCOLOR)$(tail -n 1 .weatherforecast | awk '{print toupper($1)}') $( tail -n 5 .weatherforecast | sed -n '/Update/p' | sed -e 's/^  //' -e 's/\.$//') ^fg($BGCOLOR)^bg($FGCOLOR)$output"
}
rains
