#! /bin/bash
UCITY="$1"
output="$(elinks -dump http://www.eltiempo.es/$UCITY.html)"
echo "$output" | sed     -e '/Visibilidad/,/Actualizada/ !d' \
        -e '/[a-Z]/ d' \
        -e 's/\([0-9][0-9]:[0-9][0-9]\)\ *\1\ *\1//g' \
        -e '/^$/d' \
	-e '/\[/d' \
        -e '/[0-9][0-9]:[0-9][0-9]/!d' | awk '{print $2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9"\t"$10"\t"$11"\t"$12"\t"$13"\t"$14}' | sed '1,2 d' >> ./.weatherforecast
