#! /bin/bash
#The argument is the city, if no argument is given, the weatherforecast data is updated 
if [ "$1" = "geo" ]; then UCITY="$(geolocalization)"; else
	if [ -n "$1" ]; then UCITY="$1"; else
		UCITY="`head -n 1 ./.weatherforecast | sed 's/Estas en //'`"
	fi
fi
	/home/blas/scripts/weatherfolder/download_weatherforecast "$UCITY"
	/home/blas/scripts/weatherfolder/moon_state "$UCITY"
	/home/blas/scripts/weatherfolder/sunsethour "$UCITY"
exit 0
